services:
  rcc-map-website:
    container_name: rcc-map-website
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_MAPTILER_KEY=$VITE_MAPTILER_KEY
      - VITE_DARK_MAP_ID=$VITE_DARK_MAP_ID
      - VITE_LIGHT_MAP_ID=$VITE_LIGHT_MAP_ID
      - VITE_CENTER_LAT=$VITE_CENTER_LAT
      - VITE_CENTER_LON=$VITE_CENTER_LON
    restart: unless-stopped